networks:
  my-network:
    driver: bridge

volumes:
  openldap_data:
    driver: local
  postgres-data:
    driver: local
  smtp4dev-data:
    driver: local

services:
  api_dev:
    image: ghcr.io/githiago-f/macro-sigac:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 128m
    depends_on:
      - smtp_dev
      - openldap_dev
      - dp_dev

  smtp_dev:
    image: rnwood/smtp4dev:v3
    ports:
      # Web interface (localhost only)
      - '5000:80'
      # SMTP server (localhost only)
      - '25:25'
      # IMAP server (localhost only)
      - '143:143'
      # POP3 server (localhost only)
      - '110:110'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

  db_dev:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
     - POSTGRES_PASSWORD=senhapg
     - POSTGRES_USER=usuario-pg
     - POSTGRES_DB=atividades
    volumes: 
     - postgres-data:/var/lib/postgresql/data
    mem_limit: 4g
    cpus: 0.5

  openldap_dev:
    image: lldap/lldap
    ports:
      - 3890:3890
      - 17170:17170
    environment:
      - LLDAP_JWT_SECRET=MhnXYBtz0}d!b{dzopyc<#-}7x+jCMR/
      - LLDAP_LDAP_USER_PASS=senha123
      - LLDAP_VERBOSE=true
    networks:
      - my-network
    volumes:
      - openldap_data:/data

