networks:
  my-network:
    driver: bridge

volumes:
  openldap_data:
    driver: local
  postgres-data:
    driver: local
  smtp4dev-data:
    driver: local

services:
  api_dev:
    build:
      dockerfile: ./src/main/docker/Dockerfile.jvm
      context: .
    restart: unless-stopped
    environment:
      DB_CONNECTION_URL: jdbc:postgresql://db_dev:5432/atividades 
      LDAP_URL: ldap://openldapdev:3890
    ports:
      - "80:8080"
    networks:
      - my-network
    mem_limit: 129m
    cpus: 0.2
    depends_on:
      - smtp_dev
      - openldapdev
      - db_dev

  smtp_dev:
    image: rnwood/smtp4dev:v3
    ports:
      # Web interface (localhost only)
      - '5000:80'
      # SMTP server (localhost only)
      - '25:25'
      # IMAP server (localhost only)
      - '143:143'
      # POP3 server (localhost only)
      - '110:110'
    volumes:
      - smtp4dev-data:/smtp4dev
    networks:
      - my-network
    mem_limit: 255m
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

  db_dev:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
     - POSTGRES_PASSWORD=senhapg
     - POSTGRES_USER=usuario-pg
     - POSTGRES_DB=atividades
    volumes: 
     - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network
    mem_limit: 128m
    cpus: 0.5

  openldapdev:
    image: lldap/lldap
    ports:
      - 17170:17170
    environment:
      - LLDAP_JWT_SECRET=MhnXYBtz0}d!b{dzopyc<#-}7x+jCMR/
      - LLDAP_LDAP_USER_PASS=senha123
      - LLDAP_VERBOSE=true
    networks:
      - my-network
    mem_limit: 128m
    cpus: 0.5
    volumes:
      - openldap_data:/data

