# smtp read:
# br.edu.ifrs.poa.atividades-complementares.smtp...
quarkus.security.ldap.enabled=true

quarkus.http.auth.roles-mapping."standardRole"=${LDAP_STANDARD_ROLE:aluno}

quarkus.security.ldap.dir-context.principal=${LDAP_PRINCIPAL:uid=admin,ou=system}
quarkus.security.ldap.dir-context.url=${LDAP_URL:ldaps://ldap.server.local}
quarkus.security.ldap.dir-context.password=${LDAP_PASSWORD:secret}

quarkus.security.ldap.identity-mapping.rdn-identifier=${LDAP_ATTRIBUTEMAP_RDN_IDENTIFIER:uid}
quarkus.security.ldap.identity-mapping.search-base-dn=${LDAP_ATTRIBUTEMAP_SEARCH_BASE_DN:ou=Users,dc=quarkus,dc=io}

quarkus.security.ldap.identity-mapping.attribute-mappings."cn".from=${LDAP_ATTRIBUTEMAP_CN:cn}
quarkus.security.ldap.identity-mapping.attribute-mappings."cn".filter=${LDAP_ATTRIBUTEMAP_CN_FILTER:(member=uid={0},ou=Users,dc=quarkus,dc=io)}
quarkus.security.ldap.identity-mapping.attribute-mappings."cn".filter-base-dn=${LDAP_ATTRIBUTEMAP_CN_FILTER_BASE_DN:ou=Roles,dc=quarkus,dc=io}
