br.edu.ifrs.poa.atividades-complementares.uploads-folder=${UPLOADS_FOLDER:./uploads}
default.cn.filter=(member=uid={0},ou=people,dc=example,dc=com)
default.cn.filter-base-dn=ou=groups,dc=example,dc=com
default.user-attributes.filter=(uid={0})
default.user-attributes.filter-base-dn=ou=people,dc=example,dc=com

quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.login-page=/
quarkus.http.auth.form.error-page=/?erro=true
quarkus.http.auth.form.landing-page=/atividades

quarkus.http.auth.roles-mapping."alunos"=aluno
quarkus.http.auth.roles-mapping."professores"=professor

quarkus.security.ldap.enabled=true
quarkus.security.ldap.dir-context.url=${LDAP_URL:ldap://localhost:3890}
quarkus.security.ldap.dir-context.principal=${LDAP_ADMIN_DN:uid=admin,ou=people,dc=example,dc=com}
quarkus.security.ldap.dir-context.password=${LDAP_ADMIN_PASS:senha123}

quarkus.security.ldap.identity-mapping.rdn-identifier=${LDAP_RDN_IDENTIFIER:email}
quarkus.security.ldap.identity-mapping.search-base-dn=${LDAP_SEARCH_BASE_DN:ou=people,dc=example,dc=com}

quarkus.security.ldap.identity-mapping.attribute-mappings."cn".from=${LDAP_CN_ATTRIBUTE:cn}
# desnecessario porque a prop quarkus...attribute-mappings."*".to é "groups" por padrão
# quarkus.secirity.ldap.identity-mapping.attribute-mappings."cn".to=groups
quarkus.security.ldap.identity-mapping.attribute-mappings."cn".filter=${LDAP_CN_FILTER:${default.cn.filter}}
quarkus.security.ldap.identity-mapping.attribute-mappings."cn".filter-base-dn=${LDAP_CN_BASE_DN:${default.cn.filter-base-dn}}

quarkus.security.ldap.identity-mapping.attribute-mappings."displayName".from=${LDAP_DISPLAYNAME_ATTRIBUTE:displayName}
quarkus.security.ldap.identity-mapping.attribute-mappings."displayName".to=displayName
quarkus.security.ldap.identity-mapping.attribute-mappings."displayName".filter=${LDAP_DISPLAYNAME_FILTER:${default.user-attributes.filter}}
quarkus.security.ldap.identity-mapping.attribute-mappings."displayName".filter-base-dn=${LDAP_DISPLAYNAME_BASE_DN:${default.user-attributes.filter-base-dn}}

quarkus.security.ldap.identity-mapping.attribute-mappings."email".from=${LDAP_EMAIL_ATTRIBUTE:email}
quarkus.security.ldap.identity-mapping.attribute-mappings."email".to=email
quarkus.security.ldap.identity-mapping.attribute-mappings."email".filter=${LDAP_EMAIL_FILTER:${default.user-attributes.filter}}
quarkus.security.ldap.identity-mapping.attribute-mappings."email".filter-base-dn=${LDAP_EMAIL_BASE_DN:${default.user-attributes.filter-base-dn}}

quarkus.datasource.db-kind=${DB_PROVIDER:postgresql}
quarkus.datasource.username=${DB_USER:usuario-pg}
quarkus.datasource.password=${DB_PASSWORD:senhapg}
quarkus.datasource.jdbc.url=${DB_CONNECTION_URL:jdbc:postgresql://localhost:5432/atividades}
quarkus.datasource.jdbc.max-size=${DB_POOLSIZE:10}
quarkus.hibernate-orm.schema-management.strategy=update

