# smtp reade
# br.edu.ifrs.poa.atividades-complementares.smtp...

# Elytron security (core)
# quarkus.log.category."org.wildfly.security".level=DEBUG
quarkus.log.category."org.wildfly.security.auth.realm.ldap".level=DEBUG

quarkus.security.ldap.enabled=true
quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.login-page=/
quarkus.http.auth.form.error-page=/?erro=true
quarkus.http.auth.form.landing-page=/atividades

br.edu.ifrs.poa.atividades-complementares.uploads-folder=${UPLOADS_FOLDER:./uploads}

quarkus.http.auth.roles-mapping."aluno"=${LDAP_ALUNO_ROLE:alunos}
quarkus.http.auth.roles-mapping."professor"=${LDAP_PROFESSOR_ROLE:professores}

quarkus.security.ldap.dir-context.url=${LDAP_URL:ldap://localhost:3890}
quarkus.security.ldap.dir-context.principal=${LDAP_PRINCIPAL_DN:uid=admin,ou=people,dc=example,dc=com}
quarkus.security.ldap.dir-context.password=${LDAP_PRINCIPAL_PASSWORD:senha123}

quarkus.security.ldap.identity-mapping.rdn-identifier=${LDAP_ATTRIBUTEMAP_RDN_IDENTIFIER:email}
quarkus.security.ldap.identity-mapping.search-base-dn=${LDAP_ATTRIBUTEMAP_SEARCH_BASE_DN:ou=people,dc=example,dc=com}
quarkus.security.ldap.identity-mapping.attribute-mappings."cn".from=${LDAP_ATTRIBUTEMAP_CN:cn}
quarkus.security.ldap.identity-mapping.attribute-mappings."cn".filter=(member=uid={0},${LDAP_ATTRIBUTEMAP_SEARCH_BASE_DN:ou=people,dc=example,dc=com})
quarkus.security.ldap.identity-mapping.attribute-mappings."cn".filter-base-dn=${LDAP_ATTRIBUTEMAP_CN_FILTER_BASE_DN:ou=groups,dc=example,dc=com}

quarkus.security.ldap.identity-mapping.attributes."email".from=mail
quarkus.security.ldap.identity-mapping.attributes."username".from=uid
quarkus.security.ldap.identity-mapping.attributes."fullname".from=cn

quarkus.datasource.db-kind=${DB_PROVIDER,h2}
quarkus.datasource.username=${DB_USER,user1}
quarkus.datasource.password=${DB_PASSWORD,}

quarkus.datasource.jdbc.url=${DB_CONNECTION_URL:jdbc:h2:mem:default}
quarkus.datasource.jdbc.max-size=${DB_POOLSIZE:1}
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
