FROM maven:3-eclipse-temurin-25-alpine

WORKDIR /app

COPY pom.xml ./

RUN mvn dependency:go-offline -q 2>/dev/null || true

EXPOSE 8080 5005

CMD ["mvn", "quarkus:dev", "-Dquarkus.http.host=0.0.0.0"]
